" ======My own KEY=======
" \q   toggle auto indent
" <F4> list all calls function          //cscope
" <F8> Nerdtree toggle
" <F6> Tagbar toggle                    //exuberant-ctags
" <F11> gen cscope file & connect to it //cscope
" <F7> cscope jump to file              //cscope

" =======COMMAND=============
" :cs f f RegEx   (Find file)
" :cs f e RegEx   (Find any string that conatin RegEx)

" ======motion=======
" [[ : to function head
" { : to previous blank line
" g* : search word without \<\>

" ============vimdiff===============
" ]c        : next diff
" za        : toggle current fold
" zi        : toggle ALL fold

" ============Pathogen vim plugin managment==================
call pathogen#infect()
call pathogen#helptags()

" General
set nocompatible
set diffopt+=vertical
set mouse=""

" Relate file type
filetype plugin on
set ofu=syntaxcomplete#Complete
set wildignore=*.o,*.obj,*.exe,*.so,*.lo,*.a
set ff=unix

" Performance
set lazyredraw

" Backup
set nobackup
set nowb
set noswapfile

" Search
set ignorecase
set smartcase
set incsearch
set hlsearch

" Error alarm
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Tab and space
set expandtab
set smarttab
set tabstop=4
set shiftwidth=4

" Display
set showmatch
set wildmenu
set nowrap
set nonu
set tabpagemax=50
set t_Co=256
set autoread
set cursorline
hi CursorLine cterm=none
highlight LineNr cterm=NONE ctermfg=darkgrey ctermbg=NONE
colorscheme molokai

" Highligh whitespace at end of line
highlight RedundantSpaces ctermbg=red guibg=red
match RedundantSpaces /\s\+$/

set bs=2
set ai
set tw=80
set modifiable
set winminheight=0

" Status bar
set laststatus=2
set statusline=
set statusline+=%#PmenuSel#
set statusline+=%#LineNr#
set statusline+=\ %f
set statusline+=%m\ %=
set statusline+=%#CursorColumn#
set statusline+=\ %y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\[%{&fileformat}\]
set statusline+=\ %p%%
set statusline+=\ %l:%c

highlight User1 ctermfg=red
highlight User2 term=underline cterm=underline ctermfg=green
highlight User3 term=underline cterm=underline ctermfg=yellow
highlight User4 term=underline cterm=underline ctermfg=white
highlight User5 ctermfg=cyan
highlight User6 ctermfg=white

" Menu color scheme
highlight Pmenu ctermbg=239 ctermfg=247
highlight PmenuSel ctermbg=239 ctermfg=123
highlight PmenuSbar ctermbg=darkblue
highlight PmenuThumb ctermfg=gray

" Folding
set foldenable
set foldmethod=marker
au FileType sh let g:sh_fold_enabled=5
au FileType sh let g:is_bash=1
au FileType sh set foldmethod=syntax
syntax on

" Custom key mapping

nmap <SPACE> :nohlsearch<cr>

""" keep selection after indenting/dedenting
""xnoremap < <gv
""xnoremap > >gv
""
""if version >= 700
""    " map  <C-x> :mak<cr>
""
""    " vim tab manipulation
""    map  <C-c> :tabnew<CR>
""    map <C-h> :tabprev<CR>
""    map <C-l> :tabnext<CR>
""end
""
""" disable arrow keys in normal/insert mode,
""" noremap <Up> <nop>
""" noremap <Down> <nop>
""" noremap <Left> <nop>
""" noremap <Right> <nop>
""" inoremap <Up> <nop>
""" inoremap <Down> <nop>
""" inoremap <Left> <nop>
""" inoremap <Right> <nop>
""
""" disable backspace
""" map <BS> <nop>
""" map! <BS> <nop>
""
""" disbale hjkl arrow movement
""" noremap h <nop>
""" noremap j <nop>
""" noremap k <nop>
""" noremap l <nop>
""
""" ========map the %% in Ex to current editing file's path ===========
""cnoremap <expr> %% getcmdtype( ) == ':' ?expand('%:h').'/' : '%%'
""
""" ctrl+j / ctrl+k can move the edit screen up/down
""function! s:Saving_scroll(cmd)
""  let save_scroll = &scroll
""  execute 'normal! ' . a:cmd
""  let &scroll = save_scroll
""endfunction
""nnoremap <C-J> :call <SID>Saving_scroll("1<C-V><C-D>")<CR>
""vnoremap <C-J> <Esc>:call <SID>Saving_scroll("gv1<C-V><C-D>")<CR>
""nnoremap <C-K> :call <SID>Saving_scroll("1<C-V><C-U>")<CR>
""vnoremap <C-K> <Esc>:call <SID>Saving_scroll("gv1<C-V><C-U>")<CR>
""
""" Quickfix window toggle
""command -bang -nargs=? QFix call QFixToggle(<bang>0)
""function! QFixToggle(forced)
""    if exists("g:qfix_win") && a:forced == 0
""        cclose
""        unlet g:qfix_win
""    else
""        botright copen 7
""        set nornu
""        set nu
""        let g:qfix_win = bufnr("$")
""    endif
""endfunction
""nmap <F3> :QFix<CR>
""
""
""" *****************************************************
""" ***** VIM PLUGIN & EXTERNAL EXE SETTING/MAPPING *****
""" *****************************************************
""
""" ================bazel file commentary config=============
""autocmd FileType bazel setlocal commentstring=#\ %s
""
""" ===============Nerdtree toggle==============
""nmap <F8> :NERDTreeToggle<CR>
""
""" ================Tagbar toggle==================
""nmap <F6> :TagbarToggle<CR>
""

" Automate install vim plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" VimPlug
call plug#begin()
" vim-go setting
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
Plug 'vim-scripts/taglist.vim'
call plug#end()

" Syntax Checker
let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_enable_highlighting=1

let g:syntastic_sh_checkers = ['shellcheck']
let g:syntastic_python_checkers = ['pylint', 'python']
let g:syntastic_c_checkers= ['gcc', 'make']

" Taglist
let Tlist_Compact_Format = 1
let Tlist_GainFocus_On_ToggleOpen = 1
let Tlist_Close_On_Select = 1
let Tlist_WinWidth=60
nnoremap <C-l> :TlistToggle<CR>

" Linux kernel coding style
let g:linuxsty_patterns = [ "/linux" ]
