name: Redhat UBI9 Docker Image CI

# How to trigger this workflow
on:
  push:
    branches: [ master ]
    paths:
      - 'docker/redhat/ubi9/Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
      - 'docker/redhat/ubi9/Dockerfile'
  workflow_dispatch:
  schedule:
    cron: '0 0 1 * *'

jobs:
  push_to_registry:
    name: Build and push Redhat UBI9 Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWD}}

      - name: Extract ubi9 metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: os369510/redhat-ubi9

      - name: Build and push Redhat ubi9 Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: docker/redhat/ubi9/Dockerfile
          tags: os369510/redhat-ubi9:latest
